version: "3"

services:
  telegrambot:
    container_name: telegrambot
    build: .
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    restart: always
    networks:
      - common-net
      - ext-network

  redis:
    image: ./redis-docker/
    restart: always
    ports:
      - 6379:6379
    networks:
      - common-net

networks:
  common-net:
    driver: bridge
  ext-network:
    external: true
