version: "3"

services:
  telegrambot:
    container_name: telegrambot
    build: .
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env
    command: python telegram-bot.py
    restart: always
    networks:
      - common-net
      - ext-network

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - common-net

networks:
  common-net:
    driver: bridge
  ext-network:
    external: true